repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: '.*(.log)|(.csv)'
    -   id: end-of-file-fixer
        exclude: '.*(.log)|(.csv)'
    -   id: check-yaml
    -   id: check-toml
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
        name: No commits to main or master branch
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        name: Static type check
        args:
        - --config-file=tests/mypy.ini
        - --no-warn-unused-ignores
        - --explicit-package-bases
        exclude: 'mypy_experiments.py'
        additional_dependencies:
        - mypy-extensions == 1.0.0
        - types-PyYAML == 6.0.12.12
        - types-requests == 2.31.0.8
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        name: Docstring formatting
        exclude: '__init__.py'
